package main

import (
	"fmt"
	"os"

	"github.com/yourorg/envpatch/internal/diff"
	"github.com/yourorg/envpatch/internal/merge"
	"github.com/yourorg/envpatch/internal/patch"
	"github.com/yourorg/envpatch/internal/pipeline"
	"github.com/yourorg/envpatch/internal/schema"
	"github.com/yourorg/envpatch/internal/validate"
)

// runConfig holds parsed CLI flags for the run sub-command.
type runConfig struct {
	BaseFile     string
	OverlayFile  string
	SchemaFile   string
	PatchOps     []patch.Op
	Strategy     merge.Strategy
	OutputFile   string
	Redact       bool
	PrintDiff    bool
}

// runPipeline is the entry point for the 'run' sub-command.
func runPipeline(cfg runConfig) error {
	baseRaw, err := os.ReadFile(cfg.BaseFile)
	if err != nil {
		return fmt.Errorf("reading base file: %w", err)
	}

	var overlayRaw string
	if cfg.OverlayFile != "" {
		b, err := os.ReadFile(cfg.OverlayFile)
		if err != nil {
			return fmt.Errorf("reading overlay file: %w", err)
		}
		overlayRaw = string(b)
	}

	var rules map[string]validate.Rule
	if cfg.SchemaFile != "" {
		f, err := os.Open(cfg.SchemaFile)
		if err != nil {
			return fmt.Errorf("opening schema file: %w", err)
		}
		defer f.Close()
		rules, err = schema.Load(f)
		if err != nil {
			return fmt.Errorf("loading schema: %w", err)
		}
	}

	opts := pipeline.Options{
		MergeStrategy: cfg.Strategy,
		PatchOps:      cfg.PatchOps,
		Schema:        rules,
		RedactOutput:  cfg.Redact,
	}

	result, err := pipeline.RunFromStrings(string(baseRaw), overlayRaw, opts)
	if err != nil {
		return fmt.Errorf("pipeline: %w", err)
	}

	if cfg.PrintDiff {
		fmt.Print(diff.Format(result.Diff, cfg.Redact))
	}

	for _, issue := range result.Issues {
		fmt.Fprintf(os.Stderr, "[%s] %s\n", issue.Severity, issue.Message)
	}

	out, err := pipeline.Marshal(result, "generated by envpatch", cfg.Redact)
	if err != nil {
		return fmt.Errorf("marshalling output: %w", err)
	}

	if cfg.OutputFile == "" || cfg.OutputFile == "-" {
		fmt.Print(out)
		return nil
	}
	return os.WriteFile(cfg.OutputFile, []byte(out), 0o600)
}
